// ge_globals.h

#ifndef GE_GLOBALS_H
#define GE_GLOBALS_H

#include "bn_music_item.h"
#include "bn_random.h"
#include "ge_maps.h"
#include "ge_sprites.h"
#include "ge_text.h"
#include "ge_variables.h"

using namespace bn;

constexpr int GE_PARTY_SIZE = 4;

enum action_list
{
	ACT_NONE,
	CONVO_SCENE_1,
	CONVO_GARBAGE_1,
	CONVO_GARBAGE_2,
	CONVO_GARBAGE_3,
	TO_GARBAGE_02,
	CONVO_GARBAGE_SIGN01,
	TO_VISKERS_HOUSE,
	TO_GARBAGE_03,
	TO_GARBAGE_02b,
	CONVO_VISKER_SIGN,
	CONVO_VISKER_BED,
	CONVO_VISKER_NIGHTSTAND,
	CONVO_VISKER_FOOD,
	CONVO_GARBAGE_03_SIGN,
	CONVO_VISKER_FIGHT,
	CONVO_VISKER_AFTER_FIGHT,
	TO_GARBAGE_04,
	GARBAGE_04_EXIT_01,
	GARBAGE_04_EXIT_02,
	GARBAGE_04_EXIT_03,
	GARBAGE_04_EXIT_04,
	GARBAGE_04_EXIT_05,
	CONVO_GARBAGE_04_SIGN,
	EXIT_GARBAGE_01,
	CONVO_GARBAGE_05_SIGN,
	CONVO_GARBAGE_FINAL_01,
	CONVO_LAB_RUG,
	LAB_BED,
	LAB_COMPUTER,
	LAB_BOOKSHELF,
	CONVO_LAB_GINGER,
	LAB_DOOR,
	LAB_FRIDGE,
	LAB_LOCKER,
	TO_LAB_OUTSIDE,
	CONVO_FOREST_01,
	CONVO_FOREST_01_SIGN,
	CONVO_FOREST_02,
	CONVO_CROKE_01,
	CONVO_FOREST_02_SIGN,
	TO_CAVE_01,
	CONVO_FOREST_03_SIGN,
	CONVO_FOREST_03,
	CONVO_FOREST_NOTE,
	CONVO_BRIDGE_01,
	CONVO_BRIDGE_02,
	CONVO_BRIDGE_03,
	TO_CAVE_02,
	ENTER_BG,
	EXIT_BG,
	FROM_CAVE_01,
	CONVO_CAVE_01,
	FOREST_01_SETUP,
	CONVO_CAVE_02_SIGN,
	ACT_55,
	ACT_56,
	ACT_57,
	ACT_58,
	ACT_59,
	ACT_60,
	ACT_61,
	ACT_62,
	ACT_63,
	ACT_64,
	ACT_65,
	ACT_66,
	ACT_67,
	ACT_68,
	ACT_69,
	CONVO_COWBEMMIE_01_SIGN,
	TO_FOREST_02,
	TEMMIE_01,
	TEMMIE_02,
	TEMMIE_03,
	TEMMIE_04,
	TEMMIE_05,
	TEMMIE_06,
	TEMMIE_07,
	BACK_TO_FOREST_02,
	CAVE_04_SIGN,
	TO_FOREST_03,
	BACK_TO_CAVE_03,
	TO_CAVE_04,
	TO_FOREST_02b,
	NEW_BERLIN_SIGN,
	AVALON_SIGN_01 = 87,
	AVALON_SIGN_02,
	TO_AVALON_TAVERN,
	AVALON_SIGN_VISTA,
	AVALON_SIGN_03,
	AVALON_SIGN_04,
	TO_AVALON_BUTCHER,
	AVALON_SIGN_05,
	TO_AVALON_SHOP_01,
	TO_AVALON_SHOP_02,
	CHAT_NOODLE,
	CHAT_GRANDMA,
	CHAT_COURIER,
	CHAT_PRIMARY,
	CHAT_WORMGUY,
	OUT_AVALON_SHOP_01,
	CHAT_DOLL,
	BUY_TIRE,
	BUY_ENOKI,
	BUY_BANANA,
	BUY_LIME,
	CHAT_GOAT,
	CHAT_BEAR,
	CHAT_HORSE,
	CHAT_BIRB,
	CHAT_SNEAKER,
	JUKEBOX_01,
	CHAT_ROBIN,
	CHAT_TOLLHOUSE,
	WORM_ACTION,
	FROM_AVALON_TAVERN,
	TO_SPAMTON,
	FROM_SPAMTON,
	BIG_SHOT,
	BIG_SHOT_2,
	FINAL_MSG_ACTION,
	GO_SPAMTON_GO,
	CHAT_TOLLBOOTH,
	PIT_AWAKE,
	TOGORE_TASTIC,
	PIT_TO_01,
	PIT_TO_02,
	PIT_TO_03,
	BROKEN_00,
	TO_UNKNOWN,
	BROKEN_01,
	BROKEN_02,
	BROKEN_03,
	ID_135,
	ID_136,
	ID_137,
	ID_138,
	ID_139,
	ID_140,
	ID_141,
	ID_142,
	ID_143,
	ID_144,
	ID_145,
	ID_146,
	ID_147,
	ID_148,
	ID_149,
	ID_150,
	ID_151,
	ID_152,
	ID_153,
	ID_154,
	ID_155,
	ID_156,
	ID_157,
	ID_158,
	ID_159,
	ID_160,
	DARK_INSTA,
	TO_SEBELLUS,
	SEB_PREPARE,
	SEB_CHAT_01,
	TO_DARK_PUZZLE_01,
	SEB_CHAT_02,
	TO_BUNKER,
	BUNKER_NOTE_01,
	TO_BUNKER_02,
	BUNKER_SIGN_01,
	ITEM_171,
	ITEM_172,
	ITEM_173,
	ITEM_174,
	ITEM_175,
	ITEM_176,
	ITEM_177,
	ITEM_178,
	ITEM_179,
	ITEM_180,
	ITEM_181,
	ITEM_182,
	ITEM_183,
	ITEM_184,
	FROM_BATHROOM,
	ITEM_186,
	ITEM_187,
	ITEM_188,
	ITEM_189,
	ITEM_190,
	ITEM_191,
	ITEM_192,
	ROOM_04_INIT,
	ITEM_194,
	TO_BATHROOM,
	INIT_WAKEUP,
	ITEM_197,
	TO_LIVING_WAKEUP,
	LIVING_WAKEUP_INIT,
	TO_KITCHEN_WAKEUP,
	TO_GARDEN_WAKEUP,
	TO_SHED_WAKEUP,
	SHED_INIT,
	TO_BASEMENT_WAKEUP,
	BASEMENT_INIT,
	BASEMENT_INIT_2,
	BASEMENT_FRIDGE,
	BASEMENT_TO_TUNNEL,
	TUNNEL_VISKER,
	TO_OUTSIDE_HOUSE,
	BUFFER_190b,
	CHAT_MCWEBB,
	ACTIONS_SIZE
};

enum response_list
{
	NONE,
	RESPONSES_SIZE
};

struct global_data
{
	random bn_random;
	int action_iterations[1024] = {0};
	const map *entry_map = nullptr;
	const regular_bg_item *bg = nullptr;
	vector_2 jeremy_position = {0, 0};
	vector_2 ginger_position = {0, 0};
	vector_2 sebellus_position = {0, 0};
	vector_2 kiara_position = {0, 0};
	int entry_direction = DIR_RIGHT;
	int foe = 0;
	int hp[4] = {20, 20, 20, 20};
	int max_hp[4] = {20, 20, 20, 20};
	int enemy_hp[4] = {20, 20, 20, 20};
	int enemy_max_hp[4] = {20, 20, 20, 20};
	bool progress_cue = false;
	int process_stage = 0;
	int costumes[CHAR_SIZE] = {0};
	bool items[ITEMS_SIZE] = {0};
	bool variables[VARIABLES_SIZE] = {0};
	int gold = 0;
	bool shake = 0;
	bool inverted_controls = false;

	const music_item *bg_track;
};

// Declaration only - use 'extern' keyword
extern global_data *global_data_ptr;

#endif // GE_GLOBALS_H