#ifndef GE_TYPEWRITER_AUTO_H
#define GE_TYPEWRITER_AUTO_H

enum TYPEWRITER_SCENES
{
	TYPEWRITER_INTRO,
	TYPEWRITER_INTRO2,
	TYPEWRITER_INTRO3,
	TYPEWRITER_TITLE,
	TYPEWRITER_GARBAGE,
	TYPEWRITER_MSG,
	TYPEWRITER_NEW_BERLIN,
	TYPEWRITER_DOG_AND_PONY,
	TYPEWRITER_GAME_OVER,
	TYPEWRITER_BUFFER,
	TYPEWRITER_CCUTSCENE_07,
	TYPEWRITER_CCUTSCENE_01,
	TYPEWRITER_CCUTSCENE_02,
	TYPEWRITER_CCUTSCENE_03,
	TYPEWRITER_ENDING_01_CUTSCENE_01,
	TYPEWRITER_ENDING_02_CUTSCENE_01,
	TYPEWRITER_ENDING_04_CUTSCENE_01,
};

#endif