// main_auto.h

#ifndef MAIN_AUTO_H
#define MAIN_AUTO_H

enum progress
{
	CUTSCENE_TO_GARBAGE,
	FOREST_01,
	PIT_01,
	NEW_BERLIN,
	DOG_AND_PONY,
	WAKEY_WAKEY,
	DARK_TO_DARK,
	FLAYITHRO_AWAKE,
	BLACK_TO_TRAIN,
	BLACK_TO_CANTERBURY,
	CH_CUTSCENE_07,
	CH_CUTSCENE_08,
	CH_CUTSCENE_08B,
	CH_CUTSCENE_08C,
	CUTSCENE_01,
	CH_SANS,
	CH_TITLE,
	CH_CUTSCENE_05,
	CH_CUTSCENE_09,
	CH_CUTSCENE_01,
	CH_CUTSCENE_02,
	BLACK_TO_DEATH,
	CH_CUTSCENE_06,
	KEYPAD_FAILURE,
	CH_CUTSCENE_03,
	BLACK_TO_BEACH,
	CUTSCENE_CHANNEL,
	FINAL_CHAPTER,
	ENDING_01_PART_02,
	ENDING_01_PART_03,
	ENDING_01_PART_04,
	CH_CUTSCENE_04,
	ENDING_01_PART_01,
	ENDING_02_PART_00,
	ENDING_03_PART_00,
	BLACK_TO_LAB_02,
	ENDING_04_PART_00,
	ENDING_04_PART_01,
	GAME_OVER,
	ENDING_01_PART_00,
	ENDING_00_PART_00,
};

void resolve_chapter();

#endif